server:
  port: 1221

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:1111/eureka/,http://root:root@localhost:2222/eureka/
spring:
  application:
    name: zuul
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000