server:
  port: 2222

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:1111/eureka/,http://root:root@localhost:2222/eureka/
  server:
    enable-self-preservation: true
spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root