server:
  port: 1122

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:2222/eureka/
spring:
  application:
    name: eureka-customer
