server:
  port: 1122

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:1111/eureka/,http://root:root@localhost:2222/eureka/
spring:
  application:
    name: eureka-customer
eureka-client: #被调用微服务
  ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
